name: pymc3
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8.5
  - ipython
  - arviz=0.11.2
  - theano-pymc==1.1.2
  - black
  - bokeh>=0.12.13
  - dill
  - fiona
  - graphviz>=0.8.3
  - geopandas
  - jupyterlab
  - libblas=*=*mkl
  - lxml
  - matplotlib>=3.4.1
  - mkl-service
  - numpy>=1.20.2
  - openpyxl
  - pandas>=1.2.4
  - patsy>=0.5.1
  - pip
  - pymc3=3.11.2
  - python-graphviz
  - scipy>=0.18.1
  - shapely
  - voila
  - watermark
  - xarray
  - xlrd